# Custom configuration file
# Put the folders you want to sync to the VM here.

synced_folders:
  /home/vagrant/Projects: /Users/momo/Documents/MonkeyTreeCommunity/vagrant/vagrantmonkey/Projects
  /var/www/monkeytestmoritz: /Users/momo/Documents/MonkeyTreeCommunity/MonkeyTreeSocial
