<responseData>
  <systemInfo>
    <status><?php echo $status ?></status>
    <edition><?php echo $edition?></edition>
    <zendServerVersion><?php echo $version?></zendServerVersion>
    <supportedApiVersions>
      application/vnd.zend.serverapi;version=1.2
      application/vnd.zend.serverapi;version=1.3
      application/vnd.zend.serverapi;version=1.4
      application/vnd.zend.serverapi;version=1.5
      application/vnd.zend.serverapi;version=1.6
      application/vnd.zend.serverapi;version=1.7
      application/vnd.zend.serverapi;version=1.8
      application/vnd.zend.serverapi;version=1.9
      application/vnd.zend.serverapi;version=1.10
    </supportedApiVersions>
    <phpVersion><?php echo $phpversion?></phpVersion>
    <operatingSystem><?php echo $os?></operatingSystem>
    <deploymentVersion><?php echo $deploymentversion?></deploymentVersion>
    <serverLicenseInfo><?php echo $this->licenseInfoXml($serverLicenseInfo, $numberOfNodes)?></serverLicenseInfo>
    <managerLicenseInfo><?php echo $this->licenseInfoManagerXml()?></managerLicenseInfo>
  </systemInfo>
</responseData>