"responseData":{
    "queues":[
    <?php if (isset($queues)) foreach ($queues as $cnter => $queue) { ?>
    {
    "id":"<?php echo $queue['id']; ?>",
    "name": "<?php echo htmlentities($queue['name'], ENT_NOQUOTES, 'utf-8'); ?>",
    "status": "<?php echo $queue['status']; ?>",
    "priority": "<?php echo $queue['priority']; ?>",
    "max_http_jobs": "<?php echo $queue['max_http_jobs']; ?>",
    "max_wait_time": "<?php echo $queue['max_wait_time']; ?>",
	"http_connection_timeout": "<?php echo $queue['http_connection_timeout']; ?>",
	"http_job_timeout": "<?php echo $queue['http_job_timeout']; ?>",
	"http_job_retry_count": "<?php echo $queue['http_job_retry_count']; ?>",
	"http_job_retry_timeout": "<?php echo $queue['http_job_retry_timeout']; ?>",
    "running_jobs_count": "<?php echo $queue['running_jobs_count'] ?: 0; ?>",
    "pending_jobs_count": "<?php echo $queue['pending_jobs_count'] ?: 0; ?>"
    }<?php echo $cnter < count($queues) - 1 ? ',' : ''; ?>
    <?php } ?>
    ]
}