<responseData>
	<queues>
        <?php if (isset($queues)) foreach ($queues as $queue) { ?>
        <queue>
            <id><?php echo $queue['id']; ?></id>
            <name><?php echo htmlentities($queue['name'], ENT_NOQUOTES, 'utf-8'); ?></name>
            <status><?php echo $queue['status']; ?></status>
            <priority><?php echo $queue['priority']; ?></priority>
            <max_http_jobs><?php echo $queue['max_http_jobs']; ?></max_http_jobs>
            <max_wait_time><?php echo $queue['max_wait_time']; ?></max_wait_time>
            <http_connection_timeout><?php echo $queue['http_connection_timeout']; ?></http_connection_timeout>
            <http_job_timeout><?php echo $queue['http_job_timeout']; ?></http_job_timeout>
            <http_job_retry_count><?php echo $queue['http_job_retry_count']; ?></http_job_retry_count>
            <http_job_retry_timeout><?php echo $queue['http_job_retry_timeout']; ?></http_job_retry_timeout>
            <running_jobs_count><?php echo $queue['running_jobs_count'] ?: 0; ?></running_jobs_count>
            <pending_jobs_count><?php echo $queue['pending_jobs_count'] ?: 0; ?></pending_jobs_count>
        </queue>
        <?php } ?>
	</queues>
</responseData>