<?php

namespace Audit;

interface AuditTypeInterface {

	const AUDIT_APPLICATION_DEPLOY = "AUDIT_APPLICATION_DEPLOY";
	const AUDIT_APPLICATION_REMOVE = "AUDIT_APPLICATION_REMOVE";
	const AUDIT_APPLICATION_UPGRADE = "AUDIT_APPLICATION_UPGRADE";
	const AUDIT_APPLICATION_ROLLBACK = "AUDIT_APPLICATION_ROLLBACK";
	const AUDIT_APPLICATION_REDEPLOY = "AUDIT_APPLICATION_REDEPLOY";
	const AUDIT_APPLICATION_REDEPLOY_ALL = "AUDIT_APPLICATION_REDEPLOY_ALL";
	const AUDIT_APPLICATION_DEFINE = "AUDIT_APPLICATION_DEFINE";
	
	const AUDIT_DIRECTIVES_MODIFIED = "AUDIT_DIRECTIVES_MODIFIED";
	const AUDIT_EXTENSION_ENABLED = "AUDIT_EXTENSION_ENABLED";
	const AUDIT_EXTENSION_DISABLED = "AUDIT_EXTENSION_DISABLED";
	const AUDIT_RESTART_DAEMON = "AUDIT_RESTART_DAEMON";
	const AUDIT_RESTART_PHP = 'AUDIT_RESTART_PHP';
	
	const AUDIT_GUI_AUTHENTICATION = "AUDIT_GUI_AUTHENTICATION";
	const AUDIT_GUI_CHANGE_AUTHENTICATION_SETTINGS = "AUDIT_GUI_CHANGE_AUTHENTICATION_SETTINGS";
	const AUDIT_GUI_CHANGE_PASSWORD = "AUDIT_GUI_CHANGE_PASSWORD";
	const AUDIT_GUI_AUTHORIZATION = "AUDIT_GUI_AUTHORIZATION";
	const AUDIT_GUI_AUTHENTICATION_LOGOUT = "AUDIT_GUI_AUTHENTICATION_LOGOUT";
	
	const AUDIT_GUI_AUDIT_SETTINGS_SAVE = 'AUDIT_GUI_AUDIT_SETTINGS_SAVE';
	const AUDIT_GUI_BOOTSTRAP_CREATEDB = 'AUDIT_GUI_BOOTSTRAP_CREATEDB';
	const AUDIT_GUI_BOOTSTRAP_SAVELICENSE = 'AUDIT_GUI_BOOTSTRAP_SAVELICENSE';
	
	const AUDIT_SERVER_JOIN = 'AUDIT_SERVER_JOIN';
	const AUDIT_SERVER_ADD = 'AUDIT_SERVER_ADD';
	const AUDIT_SERVER_ENABLE = 'AUDIT_SERVER_ENABLE';
	const AUDIT_SERVER_DISABLE = 'AUDIT_SERVER_DISABLE';
	const AUDIT_SERVER_REMOVE = 'AUDIT_SERVER_REMOVE';
	const AUDIT_SERVER_REMOVE_FORCE = 'AUDIT_SERVER_REMOVE_FORCE';
	const AUDIT_SERVER_RENAME = 'AUDIT_SERVER_RENAME';
	const AUDIT_SERVER_SETPASSWORD = 'AUDIT_SERVER_SETPASSWORD';
	
	const AUDIT_CODETRACING_CREATE = 'AUDIT_CODETRACING_CREATE';
	const AUDIT_CODETRACING_DELETE = 'AUDIT_CODETRACING_DELETE';
	const AUDIT_CODETRACING_DEVELOPER_ENABLE = 'AUDIT_CODETRACING_DEVELOPER_ENABLE';
	const AUDIT_CODETRACING_DEVELOPER_DISABLE = 'AUDIT_CODETRACING_DEVELOPER_DISABLE';
	
	const AUDIT_MONITOR_RULES_ENABLE = 'AUDIT_MONITOR_RULES_ENABLE';
	const AUDIT_MONITOR_RULES_DISABLE = 'AUDIT_MONITOR_RULES_DISABLE';
	const AUDIT_MONITOR_RULES_SAVE = 'AUDIT_MONITOR_RULES_SAVE';
	const AUDIT_MONITOR_RULES_ADD = 'AUDIT_MONITOR_RULES_ADD';
	const AUDIT_MONITOR_RULES_REMOVE = 'AUDIT_MONITOR_RULES_REMOVE';
	
	const AUDIT_STUDIO_DEBUG = 'AUDIT_STUDIO_DEBUG';
	const AUDIT_STUDIO_PROFILE = 'AUDIT_STUDIO_PROFILE';
	const AUDIT_STUDIO_SOURCE = 'AUDIT_STUDIO_SOURCE';
	const AUDIT_STUDIO_DEBUG_MODE_START = 'AUDIT_STUDIO_DEBUG_MODE_START';
	const AUDIT_STUDIO_DEBUG_MODE_STOP = 'AUDIT_STUDIO_DEBUG_MODE_STOP';

	const AUDIT_CLEAR_OPTIMIZER_PLUS_CACHE = 'AUDIT_CLEAR_OPTIMIZER_PLUS_CACHE';
	const AUDIT_CLEAR_DATA_CACHE_CACHE = 'AUDIT_CLEAR_DATA_CACHE_CACHE';
	const AUDIT_CLEAR_PAGE_CACHE_CACHE = 'AUDIT_CLEAR_PAGE_CACHE_CACHE';
	
	const AUDIT_PAGE_CACHE_SAVE_RULE = 'AUDIT_PAGE_CACHE_SAVE_RULE';
	const AUDIT_PAGE_CACHE_DELETE_RULES = 'AUDIT_PAGE_CACHE_DELETE_RULES';

	const AUDIT_JOB_QUEUE_SAVE_RULE = 'AUDIT_JOB_QUEUE_SAVE_RULE';
	const AUDIT_JOB_QUEUE_DELETE_RULES = 'AUDIT_JOB_QUEUE_DELETE_RULES';
	const AUDIT_JOB_QUEUE_DELETE_JOBS = 'AUDIT_JOB_QUEUE_DELETE_JOBS';
	const AUDIT_JOB_QUEUE_REQUEUE_JOBS = 'AUDIT_JOB_QUEUE_REQUEUE_JOBS';
	const AUDIT_JOB_QUEUE_RESUME_RULES = 'AUDIT_JOB_QUEUE_RESUME_RULES';
	const AUDIT_JOB_QUEUE_DISABLE_RULES = 'AUDIT_JOB_QUEUE_DISABLE_RULES';
	const AUDIT_JOB_QUEUE_RUN_NOW_RULE = 'AUDIT_JOB_QUEUE_RUN_NOW_RULE';
	
	const AUDIT_GET_PHPINFO = 'AUDIT_GET_PHPINFO';	
	const AUDIT_WEBAPI_KEY_ADD = 'AUDIT_WEBAPI_KEY_ADD';	
	const AUDIT_WEBAPI_KEY_REMOVE = 'AUDIT_WEBAPI_KEY_REMOVE';	
	
	const AUDIT_GUI_SAVELICENSE = 'AUDIT_GUI_SAVELICENSE';
	
	const AUDIT_CONFIGURATION_EXPORT = 'AUDIT_CONFIGURATION_EXPORT';
	const AUDIT_CONFIGURATION_IMPORT = 'AUDIT_CONFIGURATION_IMPORT';
	const AUDIT_CONFIGURATION_RESET = 'AUDIT_CONFIGURATION_RESET';
	
	const AUDIT_CLEAR_STATISTICS = 'AUDIT_CLEAR_STATISTICS';
	const AUDIT_RELOAD_CONFIGURATION = 'AUDIT_RELOAD_CONFIGURATION';
	
	const AUDIT_LIBRARY_REMOVE = "AUDIT_LIBRARY_REMOVE";
	const AUDIT_LIBRARY_VERSION_REMOVE = "AUDIT_LIBRARY_VERSION_REMOVE";
	const AUDIT_LIBRARY_REDEPLOY = "AUDIT_LIBRARY_REDEPLOY";
	const AUDIT_LIBRARY_DEPLOY = "AUDIT_LIBRARY_DEPLOY";
	
	const AUDIT_VHOST_ADD = 'AUDIT_VHOST_ADD';
	const AUDIT_VHOST_REMOVE = 'AUDIT_VHOST_REMOVE';
	const AUDIT_LIBRARY_SET_DEFAULT = "AUDIT_LIBRARY_SET_DEFAULT";
	
	const AUDIT_VHOST_EDIT = 'AUDIT_VHOST_EDIT';
	const AUDIT_VHOST_RESCAN = 'AUDIT_VHOST_RESCAN';
	const AUDIT_VHOST_REDEPLOY = 'AUDIT_VHOST_REDEPLOY';
	
	
	const AUDIT_VHOST_ENABLE_DEPLOYMENT = 'AUDIT_VHOST_ENABLE_DEPLOYMENT';
	const AUDIT_VHOST_DISABLE_DEPLOYMENT = 'AUDIT_VHOST_DISABLE_DEPLOYMENT';

	const AUDIT_JOB_QUEUE_ADD_JOB = 'AUDIT_JOB_QUEUE_ADD_JOB';
	
	const AUDIT_DEVELOPER_TOKEN_ADD = 'AUDIT_DEVELOPER_TOKEN_ADD';
	const AUDIT_DEVELOPER_TOKEN_REMOVE = 'AUDIT_DEVELOPER_TOKEN_REMOVE';
	
	const AUDIT_CLEAR_URL_TRACKING = 'AUDIT_CLEAR_URL_TRACKING';
	
	const AUDIT_DEVBAR_ACCESS_ELEVATE = 'AUDIT_DEVBAR_ACCESS_ELEVATE';
	const AUDIT_DEVBAR_ACCESS_DEMOTE = 'AUDIT_DEVBAR_ACCESS_DEMOTE';
	
	const AUDIT_DEVELOPER_TOKEN_EXPIRE = 'AUDIT_DEVELOPER_TOKEN_EXPIRE';
	const AUDIT_UrlInsight_RULE_ADD = 'AUDIT_UrlInsight_RULE_ADD';
	const AUDIT_UrlInsight_RULE_REMOVE = 'AUDIT_UrlInsight_RULE_REMOVE';

	const AUDIT_GUI_CHANGE_SERVER_PROFILE = 'AUDIT_GUI_CHANGE_SERVER_PROFILE';
	
	const AUDIT_PLUGIN_DEPLOY = "AUDIT_PLUGIN_DEPLOY";
	const AUDIT_PLUGIN_REMOVE = "AUDIT_PLUGIN_REMOVE";
	const AUDIT_PLUGIN_UPGRADE = "AUDIT_PLUGIN_UPGRADE";
	const AUDIT_PLUGIN_ROLLBACK = "AUDIT_PLUGIN_ROLLBACK";
	const AUDIT_PLUGIN_REDEPLOY = "AUDIT_PLUGIN_REDEPLOY";
	const AUDIT_PLUGIN_REDEPLOY_ALL = "AUDIT_PLUGIN_REDEPLOY_ALL";
	const AUDIT_PLUGIN_ENABLE = "AUDIT_PLUGIN_ENABLE";
	const AUDIT_PLUGIN_DISABLE = "AUDIT_PLUGIN_DISABLE";
	

	const AUDIT_JOB_QUEUE_ADD_QUEUE = 'AUDIT_JOB_QUEUE_ADD_QUEUE';
	const AUDIT_JOB_QUEUE_DELETE_QUEUE = 'AUDIT_JOB_QUEUE_DELETE_QUEUE';
	const AUDIT_JOB_QUEUE_UPDATE_QUEUE = 'AUDIT_JOB_QUEUE_UPDATE_QUEUE';
	
	const AUDIT_DEBUGGER_EDITED = 'AUDIT_DEBUGGER_EDITED';
	
	const AUDIT_JOB_QUEUE_QUEUES_EXPORT = 'AUDIT_JOB_QUEUE_QUEUES_EXPORT';
	const AUDIT_JOB_QUEUE_QUEUES_IMPORT = 'AUDIT_JOB_QUEUE_QUEUES_IMPORT';
	
	const AUDIT_JOB_QUEUE_SUSPEND_QUEUE = 'AUDIT_JOB_QUEUE_SUSPEND_QUEUE';
	const AUDIT_JOB_QUEUE_ACTIVATE_QUEUE = 'AUDIT_JOB_QUEUE_ACTIVATE_QUEUE';

	
	const AUDIT_ZRAY_DELETE = 'AUDIT_ZRAY_DELETE';
	
}