<?php

namespace Audit;

interface AuditTypeGroupsInterface {

	const AUDIT_GROUP_DEPLOYMENT = 'AUDIT_GROUP_DEPLOYMENT';
	const AUDIT_GROUP_CONFIGURATION = 'AUDIT_GROUP_CONFIGURATION';
	const AUDIT_GROUP_RESTART = 'AUDIT_GROUP_RESTART';
	const AUDIT_GROUP_SETTINGS_CHANGES = 'AUDIT_GROUP_SETTINGS_CHANGES';
	const AUDIT_GROUP_AUTHENTICATION = 'AUDIT_GROUP_AUTHENTICATION';
	const AUDIT_GROUP_AUTHORIZATION = 'AUDIT_GROUP_AUTHORIZATION';
	const AUDIT_GROUP_BOOTSTRAP = 'AUDIT_GROUP_BOOTSTRAP';
	const AUDIT_GROUP_CLUSTER_MANAGEMENT = 'AUDIT_GROUP_CLUSTER_MANAGEMENT';
	const AUDIT_GROUP_CODETRACING = 'AUDIT_GROUP_CODETRACING';
	const AUDIT_GROUP_MONITOR = 'AUDIT_GROUP_MONITOR';
	const AUDIT_GROUP_STUDIO = 'AUDIT_GROUP_STUDIO';
	const AUDIT_GROUP_CLEAR_CACHE = 'AUDIT_GROUP_CLEAR_CACHE';
	const AUDIT_GROUP_PAGE_CACHE_RULES = 'AUDIT_GROUP_PAGE_CACHE_RULES';
	const AUDIT_GROUP_JOBQUEUE_RULES = 'AUDIT_GROUP_JOBQUEUE_RULES';
	const AUDIT_GROUP_PHPINFO = 'AUDIT_GROUP_PHPINFO';
	const AUDIT_GROUP_WEBAPI = 'AUDIT_GROUP_WEBAPI';
	const AUDIT_GROUP_LICENSE = 'AUDIT_GROUP_LICENSE';
	const AUDIT_GROUP_DEPLOYMENT_LIBRARY = 'AUDIT_GROUP_DEPLOYMENT_LIBRARY';
	const AUDIT_GROUP_DEPLOYMENT_VHOST = 'AUDIT_GROUP_DEPLOYMENT_VHOST';
	const AUDIT_GROUP_DEVELOPER = 'AUDIT_GROUP_DEVELOPER';
	const AUDIT_GROUP_UrlInsight = 'AUDIT_GROUP_UrlInsight';
	const AUDIT_GROUP_ZRAY = 'AUDIT_GROUP_ZRAY';
}