<?php
// number of lines in the source code
$linesCount = substr_count($source, "<br />") + 1;

/** use $rowToHighLight to create a high light over row **/
?>
<style>
#highlighter{
	height:20px;
	width:100px;
	background-color: #FF0000;
	position:absolute;
	top:-3px;

	-ms-filter:"progid:DXImageTransform.Microsoft.Alpha(Opacity=40)";
	filter: alpha(opacity=40);
	-moz-opacity:0.4;
	-khtml-opacity: 0.4;
	opacity: 0.4;
}
#backtrace-showfile{
	overflow: scroll;
}
</style>

<div id="mui-source-file">
	<table cellpadding="0" cellspacing="0" width="95%" id="mui-source-file-table">
		<tr >
			<td ><?php
				for ($i=1 ; $i<=$linesCount ; ++$i) {
					$highLighter = "";
					($i == $rowToHighLight) ? $highLighter = "<div id='highlighter'></div>" : "";
					$position = "";
					($i == $rowToHighLight) ? $position = "style='position:relative;'" : "";
					echo '<code id="line_', $i,'"',$position,'>',$i,$highLighter,'</code><br />', PHP_EOL;
				}
				?></td>
			<td rowspan="<?php echo $linesCount; ?>" nowrap="nowrap"><?php echo $source; ?></td>
		</tr>
		
	</table>
	<div id="mui-source-mark"></div>
</div>