<?php $applications = $applications ?: new \ZendServer\Set(array()); ?>
<?php if (! isset($servers)) $servers = array(); ?>
<?php $limitCount = $applications->count(); ?>
"responseData":{"applicationsList":[
<?php $counter = 0; foreach($applications as $application) : /* @var $application \Deployment\Application\Container */?>
<?php   isset($servers[$application->getApplicationId()]) ? $serversData = $servers[$application->getApplicationId()] : $serversData = array();?>
<?php   echo $this->applicationInfoJson($application, $serversData);?>
<?php echo (++$counter < $limitCount ? ',' : ''); ?>
<?php endforeach ?>
]}