<div class="marketing-content">
	<div class="marketing-wrapper">
		<a href="<?php echo $this->contactZend('server-6-jobqueue-get-pricing-info'); ?>" target="_blank">
			<img alt="" src="<?php echo $this->basePath() . '/images/marketing/Job-Queue-ZS6-marketing-banner.png'; ?>" border="0"/>
		</a>
	</div>
	<div class="marketing-links-box">
		<span>Learn more about this feature:</span>
		 <div><img alt="" src="<?php echo $this->basePath() . '/images/marketing/help-icon.png'; ?>" border="0"/><a href="<?php echo $this->helplink('jobs_component') ?>" target="_blank">Zend Job Queue</a></div>
		 <div><img alt="" src="<?php echo $this->basePath() . '/images/marketing/help-icon.png'; ?>" border="0"/><a href="<?php echo $this->helplink('working_with_jobs_overview') ?>" target="_blank">Working with Jobs</a></div>
	</div>
</div>