<div class="marketing-content">
	<div class="marketing-wrapper">
		<a href="<?php echo $this->contactZend('server-6-importexport-get-pricing-info'); ?>" target="_blank">
			<img alt="" src="<?php echo $this->basePath('/images/marketing/ImportExport-ZS6-marketing-banner.png'); ?>" border="0"/>
		</a>
	</div>
	<div class="marketing-links-box import-export">
		<span><?php echo _t('Learn more about this feature:') ?></span>
		 <div><img alt="" src="<?php echo $this->basePath('/images/marketing/help-icon.png'); ?>"/><a href="<?php echo $this->helplink('importexport') ?>" target="_blank"><?php echo _t('Import/Export') ?></a></div>
		 <div><img alt="" src="<?php echo $this->basePath('/images/marketing/help-icon.png'); ?>"/><a href="<?php echo $this->helplink('restoring_and_backing_up_settings') ?>" target="_blank"><?php echo _t('Backing Up and Restoring Settings') ?></a></div>
		 <div><img alt="" src="<?php echo $this->basePath('/images/marketing/video-icon.png'); ?>"/><a class="video-link" href="http://www.zend.com/server/redirect/backing-up-and-restoring-settings-in-zend-server-6" target="_blank"><?php echo _t('Watch video') ?></a></div>
	</div>
</div>