<?php if (! isset($vhosts) || is_null($vhosts)) $vhosts = array(); ?>
<?php if (! isset($vhostsNodes) || is_null($vhostsNodes)) $vhostsNodes = array(); ?>
"responseData":{"vhostList":[
<?php $vhostsList = array(); ?>
<?php foreach($vhosts as $vhost) : ?>
<?php   $vhostsList[] = $this->json($this->vhostInfoJson($vhost, $vhostsNodes));?>
<?php endforeach ?>
<?php echo implode(',', $vhostsList); ?>
]}