<responseData>
  <serverData>
  	<phpinfo><![CDATA[<?php echo base64_encode($serverData['phpinfo']) ?>]]></phpinfo>
  	<zfversion><?php echo $serverData['zfversion'] ?></zfversion>
  	<zf2version><?php echo $serverData['zf2version'] ?></zf2version>
  	<phpversion><?php echo $serverData['phpversion'] ?></phpversion>
  	<gatewayversion><?php echo $serverData['gatewayversion'] ?></gatewayversion>
  	<toolkitversion><?php echo $serverData['toolkitversion'] ?></toolkitversion>
  	<zsversion><?php echo $serverData['zsversion'] ?></zsversion>
  	<build><?php echo $serverData['build'] ?></build>
  </serverData>
</responseData>