<responseData>
	<url><![CDATA[<?php echo $download['url']; ?>]]></url>
	<status><?php echo $this->downloadStatus($download['status']); ?></status>
	<path><![CDATA[<?php echo $download['path']; ?>]]></path>
	<message><![CDATA[<?php echo $download['message']; ?>]]></message>
	<size><?php echo $download['total']; ?></size>
	<downloaded><?php echo $download['downloaded']; ?></downloaded>
</responseData>