<div class="marketing-content">
	<div class="marketing-wrapper">
		<a href="<?php echo $this->contactZend('server-6-caching-get-pricing-info'); ?>" target="_blank">
			<img alt="" src="<?php echo $this->basePath() . '/images/marketing/Caching-Rules-ZS6-marketing-banner.png'; ?>" border="0"/>
		</a>
	</div>
	<div class="marketing-links-box page-cache">
		<span>Learn more about this feature:</span>
		 <div><img alt="" src="<?php echo $this->basePath() . '/images/marketing/help-icon.png'; ?>" border="0"/><a href="<?php echo $this->helplink('page_cache_concept') ?>" target="_blank">Zend Page Cache</a></div>
		 <div><img alt="" src="<?php echo $this->basePath() . '/images/marketing/help-icon.png'; ?>" border="0"/><a href="<?php echo $this->helplink('working_with_page_caching') ?>" target="_blank">Working with Page Caching</a></div>
		 <div><img alt="" src="<?php echo $this->basePath() . '/images/marketing/video-icon.png'; ?>" border="0"/><a class="video-link" href="http://www.zend.com/server/redirect/working-with-page-caching-in-zend-server-6" target="_blank">Watch video</a></div>
	</div>
</div>