<div class="zdb-toolbar-entry zdb-controls zdb-toolbar-button">
    <div class="zdb-toolbar-preview zdb-controls-pause" title="Pause tracking">
    	<div onclick="zendDevBar.pauseRequests()" class="zdb-toolbar-icon"></div>
        <span class="zdb-toolbar-info">&nbsp;</span>
    </div>
    <div class="zdb-toolbar-detail zdb-toolbar-detail-redundant"></div>
    <div class="zdb-toolbar-preview zdb-controls-clean zdb-toolbar-button" title="Clean request information">
    	<div onclick="zendDevBar.cleanRequests()" class="zdb-toolbar-icon"></div>
        <span class="zdb-toolbar-info">&nbsp;</span>
    </div>
    <div class="zdb-toolbar-detail zdb-toolbar-detail-redundant"></div>
</div>