<div class="zdb-toolbar-entry zdb-loading-custom zdb-toolbar-button hidden">
    <div class="zdb-toolbar-preview" title="Loading additional data">
    	<div class="zdb-toolbar-icon" style="background: transparent;">
    	   <div class="panel-spinner">
                  <div class="spinner-container container1">
                    <div class="circle1"></div>
                    <div class="circle2"></div>
                    <div class="circle3"></div>
                    <div class="circle4"></div>
                  </div>
                  <div class="spinner-container container2">
                    <div class="circle1"></div>
                    <div class="circle2"></div>
                    <div class="circle3"></div>
                    <div class="circle4"></div>
                  </div>
                  <div class="spinner-container container3">
                    <div class="circle1"></div>
                    <div class="circle2"></div>
                    <div class="circle3"></div>
                    <div class="circle4"></div>
                  </div>
                </div>
    	</div>
        <span class="zdb-toolbar-info">&nbsp; Loading additional data...</span>
    </div>
    <div class="zdb-toolbar-detail zdb-toolbar-detail-redundant"></div>
</div>