<?php if ($hasEula) : ?>
	<script type="text/javascript">
		function enableNextButton() {
			$('wizard-control-forward').set('disabled', (!$('accept-terms').checked) );
		}
	</script>
	<style>
        #accept-terms{
        	margin-top:2px;
        	margin-right:5px;			
        }
    </style>
<?php
$form->prepare();
$form->setAttribute('action', $this->url('default', array('controller' => 'Login')));
$form->setAttribute('method', 'post');
?>
		<?php echo $this->form()->openTag($form); ?>
			<dl class="zend_form">
				<?php echo $this->formElementErrors($form->get('eulaContent')); ?>
				<dd><?php echo $this->formTextarea($form->get('eulaContent')); ?></dd>
				
				<?php echo $this->formElementErrors($form->get('acceptTerms')); ?>
				<dd><?php echo $this->formCheckbox($form->get('acceptTerms')); ?></dd>
				<dt><?php echo $this->formLabel($form->get('acceptTerms')); ?></dt>
			</dl>
		<?php echo $this->form()->closeTag(); ?>
<?php endif; ?>