<?php if (isset($form)) : ?>
<?php $controller = isset($controller) ? $controller : 'Wizard' ?>
	<?php $userParamsUrl = $this->url('default', array('controller' => $controller, 'action' => 'User-Params')); ?>
	<script type="text/javascript">
	<?php if ($valid) : ?>
		userParamsValid = true;
	<?php else : ?>
		var userParamsValid = false;
	<?php endif; ?>

	function postDeploymentUserParams(wizardId) {
		dataObj = $('deployment-user-params').toObj();
		
		var valid = false;
		
		var myRequest = new Request({
			data: dataObj,
			url: '<?php echo $userParamsUrl; ?>?wizardId=' + wizardId,
			async: false,
			evalScripts: true,
			onComplete: function(response){
				valid = userParamsValid;
				if(valid){
					var errorMsgPane = $$('#userParamsPage .message-box.error')[0];
					if (errorMsgPane) { 
						errorMsgPane.addClass('hidden');
					}
				} else {
					var errorMsgPane = $$('#userParamsPage .message-box.error')[0];
					errorMsgPane.removeClass('hidden');
					errorMsgPane.set('html', "Please check the form below for errors.");
				}
				$('userParamsContent').set('html', response);
			}
		}).send();
	
		return valid;
	}
	</script>
	<div class="application-user-params">
	<?php echo $this->zendForm($form, $this->zendFormDeployWizard()); ?>
	</div>
<?php endif ?>