<responseData>
	<requestEnvironment>
		<requestId><?php echo $requestId ?></requestId>
<?php 		foreach ($superglobals as $type => $superglobalHistory):?>
		<<?php echo $type ?>><?php echo $this->superglobalStructureXml($superglobalHistory) ?></<?php echo $type ?>>
<?php 		endforeach ?>
        <rawHeaders><![CDATA[<?php echo $request->getRequestHeaders(); ?>]]></rawHeaders>
        <rawPostData><![CDATA[<?php echo $request->getHttpRawPostData(); ?>]]></rawPostData>
	</requestEnvironment>
	<responseEnvironment>
	    <rawHeaders><![CDATA[<?php echo $request->getResponseHeaders(); ?>]]></rawHeaders>
        <rawOutput><![CDATA[<?php echo $request->getRawOutput(); ?>]]></rawOutput>
	</responseEnvironment>
</responseData>
