<responseData>
	<configurations>
		<autoDetect><?php echo ($configurations['autoDetect']) ? 'true' : 'false'; ?></autoDetect>
		<useSsl><?php echo ($configurations['useSsl']) ? 'true' : 'false'; ?></useSsl>
		<autoDetectPort><?php echo $configurations['autoDetectPort']; ?></autoDetectPort>
		<autoDetectHost><![CDATA[<?php echo $configurations['autoDetectHost']; ?>]]></autoDetectHost>
		<debuggerEnabled><?php echo ($configurations['debuggerEnabled']) ? 'true' : 'false'; ?></debuggerEnabled>
		<settingsString><![CDATA[<?php echo $configurations['settingsString']; ?>]]></settingsString>
	</configurations>
</responseData>